### ISSUE TITLE
can you update the npm package of cloc into the latest version ?

### ISSUE THREAD

**Issue by sadeshwar94** [kentcdodds/cloc#12]
Hi, i would like to know whether you can update cloc npm package to the latest version of cloc https://github.com/AlDanial/cloc/releases ??  
Thank you...

**Comment by kentcdodds** [comment]
Done! It's been released as `cloc@2.4.0` on npm.

**Comment by sadeshwar94** [comment]
@kentcdodds Thank you!!!

**Comment by sadeshwar94** [comment]
Hey, 
There's a new version of cloc (https://github.com/AlDanial/cloc/releases) has been released, could you update the cloc npm package? 
Thank you.

**Comment by kentcdodds** [comment]
Done :)

**Comment by sadeshwar94** [comment]
Hi  there,
There's a new version of cloc again, could you update the cloc npm package, please.
Thank you.

**Comment by kentcdodds** [comment]
Would you like to make a PR?

**Comment by sadeshwar94** [comment]
im sorry, i dont think im capable of making of Pull request, please do check original authors cloc page. (https://github.com/AlDanial/cloc/releases).
Thank you.

**Comment by kentcdodds** [comment]
Is it because you don't know how? I can teach you how: http://makeapullrequest.com 😁

**Comment by gengjiawen** [comment]
@kentcdodds can you make a new release ? thanks.

**Comment by kentcdodds** [comment]
Sorry about that, something was wrong with CI. I've fixed that a new version has been published. Thanks for your patience!

**Comment by gengjiawen** [comment]
> Sorry about that, something was wrong with CI. I've fixed that a new version has been published. Thanks for your patience!

Thanks for the great work.
