### ISSUE TITLE
'"perl"' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by leonheess** [kentcdodds/cloc#20]
```
'"perl"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by kentcdodds** [comment]
Hi @leonheess,

You must have `perl` installed to use this package. It's literally just a distribution of a perl script.

**Comment by leonheess** [comment]
I always thought Perk could be embedded in Node.js seamlessly 🤔

**Comment by kentcdodds** [comment]
If you'd like to make it do that, be my guest 😅
