### ISSUE TITLE
Adjusting the package version

### ISSUE THREAD

**Issue by jxn-30** [kentcdodds/cloc#30]
Thanks for the auto-update of cloc (#27)!

Unfortunately, current releases will not be determined as newer due to major version 2 already existing. However I like how the cloc version is included in the Version!
Also, cloc will reach version 2 soon, as announced in [Release 1.98](https://github.com/AlDanial/cloc/releases/tag/v1.98)
> NOTE: The next release of cloc will be 2.00. Despite the major version number bump, there will be no breaking changes.

I expect this to cause issues with doubled version numbers by auto-updates.

How about introducing a new major version for this package and using cloc version for minor and patch?
So the current release would be package version `3.1.98` and the next release `3.2.0`. This keeps semver versioning but also solves the issues mentioned above.

Greetings :)

**Comment by kentcdodds** [comment]
The way we handle versions avoids issues altogether. Check the versions tab: https://www.npmjs.com/package/cloc?activeTab=versions

Thanks anyway!

**Comment by kentcdodds** [comment]
To be clear, we started adding `-cloc` to the version number

**Comment by jxn-30** [comment]
I see, thanks for your answer!
