### ISSUE TITLE
vcs option not found

### ISSUE THREAD

**Issue by montogeek** [kentcdodds/cloc#4]
Hi!

The official `cloc` library supports the `vcs` option, Could you please update it?
Thanks!

**Comment by montogeek** [comment]
This was introduced in https://github.com/AlDanial/cloc/commit/55e616e95498cf60c9cea34a2f8d34fef6d5b971
v1.7.0

I could open a PR to update it :)

**Comment by kentcdodds** [comment]
PR welcome!

**Comment by kentcdodds** [comment]
Released :+1:
