### ISSUE TITLE
cloc not counting tsx on macbook

### ISSUE THREAD

**Issue by HenrikBechmann** [kentcdodds/cloc#8]
Hi, I've installed npm install -g cloc. Installed v2.3.2, but it doesn't count .tsx code.

cloc --show-lang lists 

Teamcenter met             (met)
Teamcenter mth             (mth)
TypeScript                 (ts)
Unity-Prefab               (mat, prefab)
Vala                       (vala)
Vala Header                (vapi)

... whereas Danial's latest version https://github.com/AlDanial/cloc shows:

TTCN                       (ttcn, ttcn2, ttcn3, ttcnpp)
Twig                       (twig)
TypeScript                 (tsx, ts)
Unity-Prefab               (mat, prefab)
Vala                       (vala)

(note tsx with ts)

I presume this is a version issue. Any chance you could upgrade?

Thanks!!

**Comment by kentcdodds** [comment]
Hi @HenrikBechmann,

I don't see any newer version than 1.74 on the [cloc releases](https://github.com/AlDanial/cloc/releases) and that's the latest version available from this package. I don't want to publish anything that's not officially released yet either. Feel free to ping me when there's an official release. Thanks!

**Comment by HenrikBechmann** [comment]
sorry, turns out there was an old py version (1.62) on my macbook which was superseding the npm install. Once I purged it and re-installed your recent all is fine. Thanks!!
